spring:
   application:
      name: read_dataset
   servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB


   kafka:
      bootstrap-servers: localhost:9092
      producer:
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      
server:
   port: 8081

    
